import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { Eyebrow, PageIntro, SiteLayout, TemporaryImage } from "@/components/site";
import { team, traditional } from "@/lib/site-data";

export const Route=createFileRoute("/about")({head:()=>({meta:[{title:"About Dream Corner — Women-Led Event Studio"},{name:"description",content:"Discover Dream Corner’s story, vision and women-led approach to thoughtful event planning."},{property:"og:title",content:"About Dream Corner"},{property:"og:description",content:"The story and values behind Dream Corner’s thoughtful celebrations."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/about"}]}),component:About});
function About(){return <SiteLayout><PageIntro eyebrow="Our story · Est. 2020" title="The art of bringing celebrations to life." copy="Dream Corner began with a belief that every budget deserves care, every detail deserves attention and every celebration deserves to feel personal."/>
<section className="content-section"><div className="site-container grid gap-12 md:grid-cols-12 md:items-center"><TemporaryImage src={traditional} alt="Temporary editorial preview of a traditional event setting" className="md:col-span-6"/><div className="md:col-span-5 md:col-start-8"><Eyebrow>Dream Corner</Eyebrow><p className="prose-large mt-5">Since 2020, we have shaped occasions with creativity, precision and a deeply personal touch.</p><p className="mt-6 leading-7 text-muted-foreground">Our mission is to design and execute end-to-end events that blend premium quality with affordability, turning each event into a story worth retelling.</p></div></div></section>
<section className="section-dark"><div className="site-container editorial-split"><div><Eyebrow>Vision & mission</Eyebrow><h2>Elegance in every detail. Respect in every decision.</h2></div><div><p className="lead-light">Our vision is to inspire celebrations where every detail reflects elegance, every budget feels respected and every client walks away with memories for a lifetime.</p><p className="mt-6 text-ivory-muted">We empower women through our team, vendors and client relationships—creating a circle of growth and celebration.</p></div></div></section>
<section className="content-section"><div className="site-container"><Eyebrow>What guides us</Eyebrow><h2 className="mt-4 max-w-2xl text-4xl md:text-6xl">Values made visible in the work.</h2><div className="value-list mt-12">{["Creativity","Care","Quality","Integrity","Collaboration"].map(v=><article key={v}><h3>{v}</h3><p>Thoughtfully practiced from the first conversation through the final detail.</p></article>)}</div></div></section>
<section className="women-story"><div className="site-container grid gap-10 md:grid-cols-12 md:items-center"><TemporaryImage src={team} alt="Temporary behind-the-scenes preview of a women-led event team" className="md:col-span-6"/><div className="md:col-span-5 md:col-start-8"><Eyebrow>Women-led</Eyebrow><h2>Building a circle of opportunity and celebration.</h2><p>Our team section is ready for real names, roles and approved portraits when supplied. Until then, we will not invent the people behind the brand.</p><Link to="/contact" search={{eventType:""}} className="button-gold mt-8">Let’s create your next memory <ArrowRight size={16}/></Link></div></div></section></SiteLayout>}