import { createFileRoute } from "@tanstack/react-router";
import { useState, type FormEvent } from "react";
import { z } from "zod";
import { PageIntro, SiteLayout } from "@/components/site";
const schema=z.object({name:z.string().trim().min(2,"Please enter your full name.").max(100),email:z.string().trim().email("Please enter a valid email address.").max(255),phone:z.string().trim().min(7,"Please enter a valid phone number.").max(30),eventType:z.string().min(1,"Please select an event type."),message:z.string().trim().min(10,"Please tell us a little more about your event.").max(1500),consent:z.literal("on",{errorMap:()=>({message:"Please confirm that we may contact you."})})});
export const Route=createFileRoute("/contact")({validateSearch:(s:Record<string,unknown>)=>({eventType:typeof s.eventType==="string"?s.eventType:""}),head:()=>({meta:[{title:"Plan Your Event — Dream Corner"},{name:"description",content:"Tell Dream Corner about your celebration and begin planning an unforgettable event."},{property:"og:title",content:"Plan Your Event — Dream Corner"},{property:"og:description",content:"Share your event vision with the Dream Corner team."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"canonical",href:"/contact"}]}),component:Contact});
function Contact(){const {eventType}=Route.useSearch();const [errors,setErrors]=useState<Record<string,string>>({});const [notice,setNotice]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));const parsed=schema.safeParse(data);if(!parsed.success){setErrors(Object.fromEntries(parsed.error.issues.map(i=>[String(i.path[0]),i.message])));setNotice("");return}setErrors({});setNotice("Your enquiry is ready, but sending is not connected yet. No information has been submitted.")}
return <SiteLayout><PageIntro eyebrow="Plan your event" title="Let’s create something unforgettable." copy="Tell us a little about your celebration. Our team will get in touch to understand your vision and explore how Dream Corner can bring it to life."/><section className="content-section"><div className="site-container grid gap-12 md:grid-cols-12"><div className="md:col-span-4"><h2 className="text-3xl">Start with what you know.</h2><p className="mt-5 leading-7 text-muted-foreground">A date can be flexible. A guest count can be approximate. Share the feeling you want to create, and the details can follow.</p><div className="form-note mt-8">This form is currently a polished preview. It needs an email, CRM or database connection before enquiries can be delivered.</div></div><form className="form-grid md:col-span-7 md:col-start-6" onSubmit={submit} noValidate>
{[["name","Full Name *","text","Your full name"],["email","Email Address *","email","you@example.com"],["phone","Phone Number *","tel","Your phone number"],["date","Preferred Event Date","date",""]].map(([n,l,t,p])=><div className="field" key={n}><label htmlFor={n}>{l}</label><input id={n} name={n} type={t} placeholder={p}/>{errors[n]&&<p className="field-error">{errors[n]}</p>}</div>)}
<div className="field"><label htmlFor="eventType">Event Type *</label><select id="eventType" name="eventType" defaultValue={eventType}><option value="">Select an event</option>{["Themed Birthday","Traditional Event","Wedding Event","Corporate Event","Add-ons","Other"].map(o=><option key={o}>{o}</option>)}</select>{errors.eventType&&<p className="field-error">{errors.eventType}</p>}</div>
{[["location","Event Location / City","Where are you celebrating?"],["guests","Estimated Guest Count","Approximate number"],["budget","Approximate Budget Range","Your preferred range"],["referral","How did you hear about us?","Optional"]].map(([n,l,p])=><div className="field" key={n}><label htmlFor={n}>{l}</label><input id={n} name={n} placeholder={p}/></div>)}
<div className="field field-wide"><label htmlFor="message">Tell Us About Your Event *</label><textarea id="message" name="message" placeholder="Share the occasion, your ideas and what matters most to you." maxLength={1500}/>{errors.message&&<p className="field-error">{errors.message}</p>}</div>
<label className="consent field-wide"><input name="consent" type="checkbox"/><span>I consent to being contacted about this enquiry.</span></label>{errors.consent&&<p className="field-error field-wide">{errors.consent}</p>}
<button className="button-primary field-wide" type="submit">Prepare My Enquiry</button>{notice&&<div className="form-note field-wide" role="status">{notice}</div>}
</form></div></section></SiteLayout>}